/** Stylelint para CSS (y CSS Modules) con ordenación y validaciones sólidas */
module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  plugins: [
    'stylelint-order',
    'stylelint-no-unsupported-browser-features',
    'stylelint-declaration-block-no-ignored-properties',
    'stylelint-csstree-validator',
  ],
  rules: {
    /* Calidad / consistencia */
    'color-function-notation': 'modern',
    'alpha-value-notation': 'percentage',
    'media-feature-range-notation': 'context',
    'font-weight-notation': 'numeric',
    'selector-class-pattern': '^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$', // kebab-case

    /* Compatibilidad (ajusta "browserslist" en package.json) */
    'plugin/no-unsupported-browser-features': [
      true,
      {
        severity: 'warning',
        ignorePartialSupport: true,
      },
    ],

    /* Duplicados/propiedades ignoradas/validador */
    'plugin/declaration-block-no-ignored-properties': true,
    'csstree/validator': true,

    /* Orden recomendado por grupos (modifícalo a tu gusto) */
    'order/properties-order': [
      {
        groupName: 'positioning',
        properties: ['position', 'inset', 'top', 'right', 'bottom', 'left', 'z-index'],
      },
      {
        groupName: 'box-model',
        properties: [
          'display',
          'contain',
          'float',
          'clear',
          'box-sizing',
          'width',
          'min-width',
          'max-width',
          'height',
          'min-height',
          'max-height',
          'aspect-ratio',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'overflow',
          'overflow-x',
          'overflow-y',
        ],
      },
      {
        groupName: 'flex-grid',
        properties: [
          'flex',
          'flex-grow',
          'flex-shrink',
          'flex-basis',
          'flex-flow',
          'flex-direction',
          'flex-wrap',
          'order',
          'align-items',
          'align-content',
          'align-self',
          'justify-items',
          'justify-content',
          'justify-self',
          'gap',
          'row-gap',
          'column-gap',
          'grid',
          'grid-area',
          'grid-template',
          'grid-template-areas',
          'grid-template-rows',
          'grid-template-columns',
          'grid-row',
          'grid-row-start',
          'grid-row-end',
          'grid-column',
          'grid-column-start',
          'grid-column-end',
          'place-items',
          'place-content',
          'place-self',
        ],
      },
      {
        groupName: 'typography',
        properties: [
          'font',
          'font-family',
          'font-size',
          'font-weight',
          'font-style',
          'font-variant',
          'line-height',
          'letter-spacing',
          'text-align',
          'text-wrap',
          'text-overflow',
          'white-space',
          'text-transform',
          'text-decoration',
          'text-shadow',
          'color',
        ],
      },
      {
        groupName: 'visual',
        properties: [
          'background',
          'background-color',
          'background-image',
          'background-position',
          'background-size',
          'background-repeat',
          'border',
          'border-radius',
          'border-width',
          'border-style',
          'border-color',
          'outline',
          'outline-offset',
          'box-shadow',
          'opacity',
          'mix-blend-mode',
          'filter',
          'backdrop-filter',
        ],
      },
      {
        groupName: 'animation',
        properties: [
          'transform',
          'transform-origin',
          'transition',
          'transition-property',
          'transition-duration',
          'transition-timing-function',
          'transition-delay',
          'animation',
          'animation-name',
          'animation-duration',
          'animation-timing-function',
          'animation-delay',
          'animation-iteration-count',
          'animation-direction',
          'animation-fill-mode',
          'will-change',
        ],
      },
      'cursor',
      'pointer-events',
      'visibility',
    ],
  },
  overrides: [
    /* Permitir :global/:local y nombres libres en CSS Modules */
    {
      files: ['**/*.module.css'],
      rules: { 'selector-class-pattern': null },
    },
  ],
};
